Update constants path for PS Versions >= 8.1
PrestaShop/open-source pull request #126
Opened 2022-10-07 15:57 UTC by FabienPapet

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Documentation for https://github.com/PrestaShop/PrestaShop/pull/29750/

2022-10-07 19:45 UTC, matks reviewed
All good, now waiting for core PR to be merged

2022-10-10 09:22 UTC, eternoendless requested changes

2022-10-10 09:22 UTC, eternoendless commented on content/maintainers-guide/releasing-prestashop/preliminary-tasks.md
> +
```suggestion
{{% notice tip %}}
Starting with Prestashop 8.1, version constants are located in `src/Core/Version.php`.
{{% /notice %}}

```

2022-10-13 10:43 UTC, jolelievre approved these changes

2022-10-28 14:13 UTC, FabienPapet commented
Branch has been merged, can we merge this ?

2022-10-31 18:35 UTC, eternoendless commented
Thank you @FabienPapet

2022-10-31 18:35 UTC, merged