Wip User groups
PrestaShop/open-source pull request #161
Opened 2023-02-23 15:47 UTC by okom3pom

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket | @coffrep

2023-02-23 16:09 UTC, PrestaEdit commented on content/user-groups/_index.md
> +Every year, Friend of Presta (FoP) organizes a day of conferences and workshops that bring together developers, integrators, and members of the PrestaShop open-source team.
```suggestion
Every year, Friends of Presta (FoP) organizes a day of conferences and workshops that bring together developers, integrators, and members of the PrestaShop open-source team.
```

2023-02-23 16:09 UTC, PrestaEdit commented on content/user-groups/_index.md
> +![Friend of Presta](fop_logotype-horizontal-blanc-avec-fond.svg)
```suggestion
![Friends of Presta](fop_logotype-horizontal-blanc-avec-fond.svg)
```

2023-02-24 14:27 UTC, coffrep requested changes
Hi - thanks for adding FoP to this page. I just added a few suggestions, do let me know of your thoughts!

2023-02-24 14:27 UTC, coffrep commented on content/user-groups/_index.md
> +FoP manages a Slack channel and a Facebook page that has attracted thousands of members who share a passion for PrestaShop
```suggestion
FoP manages a Slack channel and a Facebook page, attracting thousands of members who share a passion for PrestaShop.
```

2023-02-24 14:27 UTC, coffrep commented on content/user-groups/_index.md
> +You can also join our security team for a safer e-commerce (more than 50 flaws reported on third party modules). And many projects on our [Github](https://github.com/friends-of-presta) including the
```suggestion
You can also join the organization's security team for a safer e-commerce (more than 50 flaws reported on third party modules). And many projects on [GitHub](https://github.com/friends-of-presta) including the [FoP Console](https://github.com/friends-of-presta/fop_console).
```

2023-02-24 14:27 UTC, coffrep commented on content/user-groups/_index.md
> +Friends of Presta is a French community that unites developers and integrators who work with the open-source e-commerce platform PrestaShop.
```suggestion
Friends of Presta is a French community that connects developers and integrators who work with the open-source e-commerce platform PrestaShop.
```

2023-02-24 14:27 UTC, coffrep commented on content/user-groups/_index.md
> +[Join us to become a part of this community and help us improve PrestaShop!](https://friendsofpresta.org/en)
```suggestion
[Join FoP to become a part of the community and help improve PrestaShop!](https://friendsofpresta.org/en)
```

2023-02-24 15:24 UTC, coffrep approved these changes

2023-02-24 19:54 UTC, PrestaEdit approved these changes

2023-02-27 08:32 UTC, mflasquin approved these changes

2023-02-27 08:32 UTC, merged