Add Release manager
PrestaShop/open-source pull request #228
Opened 2023-10-12 13:42 UTC by AureRita

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | I add the documentation of release manager on quality council  
| Fixed ticket | NA

2023-10-13 07:19 UTC, nicosomb requested changes

2023-10-13 07:19 UTC, nicosomb commented on content/project-organization/quality-council/processes/release-manager.md
> +---
duplicate content?

2023-10-13 07:19 UTC, nicosomb commented on content/project-organization/quality-council/processes/release-manager.md
> +Translated with www.DeepL.com/Translator (free version)
you can remove this line

2023-10-13 07:19 UTC, nicosomb commented on content/project-organization/quality-council/processes/release-manager.md
> +![Untitled](images/release_manager_img_1.png)
please add a title for each picture, instead of "Untitled".

2023-10-13 08:55 UTC, AureRita commented
I apply the different changes you asked for

2023-10-13 09:42 UTC, nicosomb approved these changes

2023-10-17 16:18 UTC, matthieu-rolland approved these changes

2023-10-17 16:35 UTC, boherm approved these changes

2023-10-31 06:34 UTC, Robin-Fischer-PS requested changes
You should delete all the images not used in the documentation :)

2023-10-31 06:34 UTC, Robin-Fischer-PS commented on content/project-organization/quality-council/processes/release-manager.md
> +The purpose of this page is to explain how to create these different tickets before carrying out a release.
```suggestion
Although these tickets are currently created on an internal company Jira, the purpose of this documentation is to explain what information is needed to prepare the release, and how to obtain it, before carrying out a release.
```

2023-10-31 06:34 UTC, Robin-Fischer-PS commented on content/project-organization/quality-council/processes/release-manager.md
> +Before even starting to create a ticket in Jira, you need to find out about the release you're going to test.
```suggestion
The first thing to do is to find out about the release you're going to test. 
```

2023-10-31 06:34 UTC, Robin-Fischer-PS commented on content/project-organization/quality-council/processes/release-manager.md
> +You now know all the PRs in your release. It's highly recommended that you check them all to find out what these PRs might affect.
```suggestion
You now have the list of all the PRs merged in your release. It's highly recommended that you check them all to find out what these PRs might affect. 
```

2023-10-31 06:34 UTC, Robin-Fischer-PS commented on content/project-organization/quality-council/processes/release-manager.md
> +If you've followed all these steps, you should now have your list for Test Plan and Test Execution, which you can share with your team members and developers.
```suggestion
If you've followed all these steps, you should now have your list of test scenarios which should be tested for this release, which you can share with your team members and developers. 
```

2023-10-31 13:55 UTC, Robin-Fischer-PS approved these changes
LGTM :)

2023-11-13 10:49 UTC, merged