Update manual steps in release process
PrestaShop/open-source pull request #281
Opened 2024-12-20 09:40 UTC by nicosomb

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Update manual steps in release process
| Fixed ticket | N/A

2024-12-20 09:43 UTC, boherm approved these changes

2024-12-20 09:55 UTC, jolelievre requested changes

2024-12-20 09:55 UTC, jolelievre commented on content/maintainers-guide/processes/release/prestashop/preliminary-tasks.md
> +* Please execute `composer audit` to check vulnerabilities.
Ok for the replacement for security
However, we should let the steps for version 8.* and indicate that they are no longer need for versions 9+

2024-12-20 15:09 UTC, jolelievre commented on content/maintainers-guide/processes/release/prestashop/preliminary-tasks.md
> -  ```
This part mus be kept, but mentioning it is only necessary until 8.2

2024-12-20 15:09 UTC, jolelievre commented on content/maintainers-guide/processes/release/prestashop/preliminary-tasks.md
> -  ```
php bin/console prestashop:linter:security-annotation
  php bin/console prestashop:linter:legacy-link

2024-12-20 15:55 UTC, Hlavtox submitted a review, later dismissed

2025-02-26 11:51 UTC, jolelievre requested changes

2025-02-26 11:51 UTC, jolelievre commented on content/maintainers-guide/processes/release/prestashop/preliminary-tasks.md
> +* Before PrestaShop 9.x: all controllers are secured by annotations, and legacy link are provided for Symfony routes:
```suggestion
* All controllers are secured by annotations, and legacy link are provided for Symfony routes (starying from 9.0.x this step is obsolete as it is checked in the CI already):
```

2025-02-26 11:51 UTC, jolelievre commented on content/maintainers-guide/processes/release/prestashop/preliminary-tasks.md
> +* For PrestaShop 9.x and above: please execute `composer audit` to check vulnerabilities.
```suggestion

* There are no known vulnerabilities in composer dependencies using `composer audit` to check vulnerabilities.
```

2025-03-02 20:27 UTC, matks commented on content/maintainers-guide/processes/release/prestashop/preliminary-tasks.md
> +* All controllers are secured by annotations, and legacy link are provided for Symfony routes (starying from 9.0.x this step is obsolete as it is checked in the CI already):
```suggestion
* All controllers are secured by annotations, and legacy link are provided for Symfony routes (starting from 9.0.x this step is obsolete as it is checked in the CI already):
```

2025-03-02 20:28 UTC, matks commented
Thank you @nicosomb

2025-03-02 20:28 UTC, merged