Add support page
PrestaShop/open-source pull request #77
Opened 2022-02-14 19:45 UTC by eternoendless

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Add a page to help people find support resources

2022-02-15 07:37 UTC, Progi1984 commented on content/support/_index.md
> +* [PrestaShop partner agencies and experts](https://www.prestashop.com/experts)
```suggestion
```

2022-02-15 07:37 UTC, Progi1984 commented on content/support/_index.md
> +* [Training courses](https://www.prestashop.com/training)
```suggestion
```

2022-02-15 07:41 UTC, Progi1984 requested changes
Two small comments.

I remove all links to prestashop.com in waiting for how PrestaShop.com and all foundations members will be gain to invest in project. May be @ow2 can answer to that.

2022-02-18 17:17 UTC, matks commented on content/support/_index.md
> +* [PrestaShop partner agencies and experts](https://www.prestashop.com/experts)
I disagree with removing the link, but I think the link should be clear whether it's PrestaShop company or PrestaShop project.

```suggestion
* [PrestaShop SA partner agencies and experts](https://www.prestashop.com/experts)
```

2022-02-18 17:17 UTC, matks commented on content/support/_index.md
> +* [Training courses](https://www.prestashop.com/training)
Similarly to what I said previously
```suggestion
* [PrestaShop SA training courses](https://www.prestashop.com/training)
```

2022-02-18 18:32 UTC, eternoendless commented on content/support/_index.md
> +* [PrestaShop partner agencies and experts](https://www.prestashop.com/experts)
How about this?
```suggestion
* [List of agencies and experts](https://www.prestashop.com/experts) (sponsored by PrestaShop SA)
```

2022-02-18 20:59 UTC, matks commented on content/support/_index.md
> +* [Training courses](https://www.prestashop.com/training)
Better 👍

2022-02-18 20:59 UTC, matks commented on content/support/_index.md
> +* [PrestaShop partner agencies and experts](https://www.prestashop.com/experts)
Better 👍

2022-02-19 12:04 UTC, okom3pom approved these changes

2022-02-19 12:04 UTC, okom3pom commented on content/support/_index.md
> +* [Training courses](https://www.prestashop.com/training)
404 error you need to add `/en/` but i also agree @Progi1984

2022-02-19 12:04 UTC, okom3pom commented on content/support/_index.md
> +* [PrestaShop partner agencies and experts](https://www.prestashop.com/experts)
404 error you need to add `/en/` but i also agree @Progi1984

2022-02-22 10:36 UTC, matks commented
Drupal does this and it's fine
https://www.drupal.org/drupal-services
https://www.drupal.org/docs/troubleshooting-drupal/how-to-ask-for-support-from-the-drupal-community

2022-02-25 08:14 UTC, Progi1984 approved these changes

2022-02-25 08:23 UTC, matks approved these changes
Minor issue but it's mergeable IMO

2022-02-25 08:23 UTC, matks commented on content/support/_index.md
> +If you need serious help with your project, your best choice is to get contact a professional. There are thousands of agencies and freelance experts located around the globe:
"your best choice is to get contact a professional"

I think maybe there's a little typo here?

-> your best choice is to get in touch with a professional
-> your best choice is to contact a professional

2022-02-25 18:13 UTC, eternoendless commented on content/support/_index.md
> +If you need serious help with your project, your best choice is to get contact a professional. There are thousands of agencies and freelance experts located around the globe:
Good catch, thanks
```suggestion
If you need serious help with your project, your best choice is to contact a professional. There are thousands of agencies and freelance experts located around the globe:
```

2022-02-25 18:15 UTC, eternoendless commented on content/support/_index.md
> +# I need help with PrestaShop
```suggestion
# Get help with PrestaShop
```

2022-02-26 20:37 UTC, matks approved these changes

2022-02-28 07:40 UTC, PierreRambaud approved these changes

2022-02-28 07:41 UTC, merged